Need more work,
trying to fix this script

diff --git a/work/ci-operator-get-access b/work/ci-operator-get-access
--- a/work/ci-operator-get-access
+++ b/work/ci-operator-get-access
@@ -4,7 +4,7 @@
 set -e
 
 
-JOB_NAME=${1:-"e2e-aws-ocp-41"}
+JOB_NAME=${1:-"e2e"}
 KOUTPUT="${HOME}/.kube/config.ci-operator"
 
 TMP=$(mktemp /tmp/.mm.XXXXXX)
@@ -58,58 +58,50 @@ oc whoami --show-server=true|grep -q api.ci.openshift.org || {
     exit 1
 }
 
+
+project=$(oc get project |grep '^ci-op'|fzf -1|awk '{print $1}')
+if [[ -z ${project} ]];then
+    echo "I could not find any project that starts with ci-op in the list of projects"
+    echo "something is fishy in there."
+    exit 1
+fi
+
 _cnt=0
 echo "Waiting for pods with prefix ${JOB_NAME} to comes up.."
 while True;do
-    _ciprojects=$(oc get project|grep '^ci-op'|sed 's/ .*//' || true)
-    for _cip in ${_ciprojects};do
-        e2e_test_pod=$(oc get pod -n ${_cip} -o name|grep "^pod/${JOB_NAME}" || true)
-        [[ -n ${e2e_test_pod} ]] && {
-            ci_prjs="${ci_prj} ${_cip}"
-        }
-    done
-    [[ -n ${ci_prjs} ]] && break
-    [[ ${_cnt} == 50 ]] && { echo "We can't find no pod with prefix ${JOB_NAME}"; exit 1 ;}
+    job_pod=$(oc get pod -n ${project} -o name|grep "^pod/${JOB_NAME}" || true)
+    [[ -n ${job_pod} ]] && {
+        break
+    }
+    [[ ${_cnt} == 60 ]] && { echo "We can't find no pod with prefix ${JOB_NAME}"; exit 1 ;}
     (( _cnt++ ))
-    sleep 3
+    sleep 5
 done
 
 
-set -x
-_arr=(`echo ${ci_prjs}`)
-if [[ ${#_arr[@]} > 1 ]]; then
-    ci_prj=$(oc get project ${ci_prjs} --sort-by=.metadata.creationTimestamp --no-headers --template='{{ range .items  }}{{ printf "%s -- %s\n" .metadata.name .metadata.creationTimestamp  }}{{ end }}'|fzf --tac -1)
-    ci_prj=${ci_prj%% *}
-else
-    ci_prj=${ci_prjs}
-fi
-
-echo "Found it in namespace ${ci_prj} ...."
-
-wait_and_log ${ci_prj} ${e2e_test_pod} setup ".*Access the OpenShift web-console here.*"
+echo "Found pod ${JOB_NAME} in namespace ${project} ...."
+wait_and_log ${project} ${JOB_NAME} setup ".*Access the OpenShift web-console here.*"
 
 clusterurl=$(egrep 'Access the OpenShift web-console here.*(https.*)"' ${TMP}|sed 's%.*https%https%;s/"$//')
 terminal-notifier -title 'Cluster has started' -message "CI has been Built on ${clusterurl}" -appIcon /Users/chmouel/Downloads/centos.png -open "${clusterurl}" -ignoreDnD
 
-set -x
-oc rsh -n ${ci_prj} -c lease ${e2e_test_pod} cat /tmp/artifacts/installer/auth/kubeconfig > ${KOUTPUT}
-set +x
+oc rsh -n ${project} -c test ${JOB_NAME} cat /tmp/artifacts/installer/auth/kubeconfig > ${KOUTPUT}
 echo
 echo "You can access the cluster with this kubeconfig:"
 echo export KUBECONFIG=${KOUTPUT}
 echo
 
-wait_and_log ${ci_prj} ${e2e_test_pod} "test" ".*E2E TESTS PASSED.*"
+wait_and_log ${project} ${JOB_NAME} "test" ".*E2E TESTS PASSED.*"
 
 echo export KUBECONFIG=${KOUTPUT}
 
 export KUBECONFIG=${KOUTPUT}
-# Probably knative/tekton specific so you may not need it so fel free to rip this off,
-for p in $(oc get project -o name|grep arendelle|sed 's/.*\///');do
-    output=$(oc get pod -o name -n $p 2>/dev/null)
-    [[ -n ${output} ]] && {
-        oc project ${p}
-        oc describe "${output}"
-        break
-    }
-done
+# # Probably knative/tekton specific so you may not need it so fel free to rip this off,
+# for p in $(oc get project -o name|grep arendelle|sed 's/.*\///');do
+#     output=$(oc get pod -o name -n $p 2>/dev/null)
+#     [[ -n ${output} ]] && {
+#         oc project ${p}
+#         oc describe "${output}"
+#         break
+#     }
+# done
